import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Exemplo de Boyler-Plaet",
  description: "Generated by create next app",
};

export const viewport = {
  width:"device-width", 
  initialScale:1.0,
  colorScehme:"dark"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
