import type { Metadata } from "next";
import Rodape from "./components/Rodape/Rodape";
import Cabecalho from "./components/Cabecalho/Cabecalho";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
  colorScheme: "dark"
} 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
