import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Footer from "@/components/Footer/Footer";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Aula 11",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale:1.0,
  colorScheme:"dark"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/>
        {children}
        <Footer/>
      </body>  
      
      
    </html>
  );
}
