import type { Metadata } from "next";
import Cabecalho from "./components/cabecalho/Cabecalho";
import Rodape from "./components/rodape/Rodape";


export const metadata: Metadata = {
  title:"Create Next App",
  description: "Generated by",
}

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
  colorScheme: "dark"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/>
         {children}
        <Rodape/>
      </body>
    </html>
  );
}
